In [66]:
import pandas as pd

person_df = pd.read_csv("FARS2020NationalCSV/person.csv", encoding='latin-1')

In [39]:
print(person_df.info())
print(person_df.dtypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85885 entries, 0 to 85884
Columns: 121 entries, STATE to ICFINALBODYNAME
dtypes: float64(13), int64(51), object(57)
memory usage: 79.3+ MB
None
STATE                  int64
STATENAME             object
ST_CASE                int64
VE_FORMS               int64
VEH_NO                 int64
                      ...
VPICMODELNAME         object
VPICBODYCLASS        float64
VPICBODYCLASSNAME     object
ICFINALBODY          float64
ICFINALBODYNAME       object
Length: 121, dtype: object

In [67]:
person_df = person_df.iloc[:101, [1,2,3,4,5,6,7,8,9,10]]
pd.set_option('display.max_rows', 200)
person_df

,STATENAME,ST_CASE,VE_FORMS,VEH_NO,PER_NO,STR_VEH,COUNTY,DAY,DAYNAME,MONTH
0,Alabama,10001,1,1,1,0,51,1,1,1
1,Alabama,10001,1,1,2,0,51,1,1,1
2,Alabama,10001,1,1,3,0,51,1,1,1
3,Alabama,10001,1,1,4,0,51,1,1,1
4,Alabama,10002,4,1,1,0,73,2,2,1
5,Alabama,10002,4,1,2,0,73,2,2,1
6,Alabama,10002,4,2,1,0,73,2,2,1
7,Alabama,10002,4,3,1,0,73,2,2,1
8,Alabama,10002,4,3,2,0,73,2,2,1
9,Alabama,10002,4,4,1,0,73,2,2,1
10,Alabama,10003,2,1,1,0,117,2,2,1
11,Alabama,10003,2,2,1,0,117,2,2,1
12,Alabama,10004,1,1,1,0,15,3,3,1
13,Alabama,10004,1,1,2,0,15,3,3,1
14,Alabama,10004,1,1,3,0,15,3,3,1
15,Alabama,10004,1,1,4,0,15,3,3,1
16,Alabama,10004,1,1,5,0,15,3,3,1
17,Alabama,10005,1,1,1,0,37,4,4,1
18,Alabama,10006,2,1,1,0,103,4,4,1
19,Alabama,10006,2,2,1,0,103,4,4,1
20,Alabama,10006,2,2,2,0,103,4,4,1
21,Alabama,10007,1,0,1,1,73,7,7,1
22,Alabama,10007,1,1,1,0,73,7,7,1
23,Alabama,10008,2,1,1,0,25,8,8,1
24,Alabama,10008,2,2,1,0,25,8,8,1
25,Alabama,10009,2,1,1,0,45,9,9,1
26,Alabama,10009,2,2,1,0,45,9,9,1
27,Alabama,10009,2,2,2,0,45,9,9,1
28,Alabama,10009,2,2,3,0,45,9,9,1
29,Alabama,10010,2,1,1,0,95,10,10,1
30,Alabama,10010,2,1,2,0,95,10,10,1
31,Alabama,10010,2,2,1,0,95,10,10,1
32,Alabama,10011,2,1,1,0,79,10,10,1
33,Alabama,10011,2,2,1,0,79,10,10,1
34,Alabama,10011,2,2,2,0,79,10,10,1
35,Alabama,10012,2,1,1,0,73,11,11,1
36,Alabama,10012,2,2,1,0,73,11,11,1
37,Alabama,10013,1,0,1,1,125,13,13,1
38,Alabama,10013,1,1,1,0,125,13,13,1
39,Alabama,10014,1,1,1,0,53,13,13,1
40,Alabama,10015,1,0,1,1,61,13,13,1
41,Alabama,10015,1,1,1,0,61,13,13,1
42,Alabama,10016,2,1,1,0,43,13,13,1
43,Alabama,10016,2,1,2,0,43,13,13,1
44,Alabama,10016,2,2,1,0,43,13,13,1
45,Alabama,10017,2,0,1,1,73,13,13,1
46,Alabama,10017,2,1,1,0,73,13,13,1
47,Alabama,10017,2,2,1,0,73,13,13,1
48,Alabama,10018,2,1,1,0,43,14,14,1
49,Alabama,10018,2,2,1,0,43,14,14,1
50,Alabama,10018,2,2,2,0,43,14,14,1
51,Alabama,10018,2,2,3,0,43,14,14,1
52,Alabama,10019,1,1,1,0,113,14,14,1
53,Alabama,10020,1,1,1,0,73,15,15,1
54,Alabama,10021,2,1,1,0,97,16,16,1
55,Alabama,10021,2,2,1,0,97,16,16,1
56,Alabama,10022,1,1,1,0,9,16,16,1
57,Alabama,10022,1,1,2,0,9,16,16,1
58,Alabama,10023,1,1,1,0,93,17,17,1
59,Alabama,10024,2,1,1,0,81,17,17,1
60,Alabama,10024,2,2,1,0,81,17,17,1
61,Alabama,10025,1,1,1,0,77,17,17,1
62,Alabama,10026,2,1,1,0,115,17,17,1
63,Alabama,10026,2,2,1,0,115,17,17,1
64,Alabama,10026,2,2,2,0,115,17,17,1
65,Alabama,10027,1,1,1,0,129,18,18,1
66,Alabama,10027,1,1,2,0,129,18,18,1
67,Alabama,10028,1,1,1,0,73,17,17,1
68,Alabama,10028,1,1,2,0,73,17,17,1
69,Alabama,10028,1,1,3,0,73,17,17,1
70,Alabama,10029,1,0,1,1,97,12,12,1
71,Alabama,10029,1,1,1,0,97,12,12,1
72,Alabama,10030,2,1,1,0,87,11,11,1
73,Alabama,10030,2,2,1,0,87,11,11,1
74,Alabama,10030,2,2,2,0,87,11,11,1
75,Alabama,10031,3,1,1,0,115,17,17,2
76,Alabama,10031,3,2,1,0,115,17,17,2
77,Alabama,10031,3,2,2,0,115,17,17,2
78,Alabama,10031,3,3,1,0,115,17,17,2
79,Alabama,10032,1,1,1,0,73,17,17,2
80,Alabama,10032,1,2,1,0,73,17,17,2
81,Alabama,10033,1,1,1,0,3,14,14,2
82,Alabama,10033,1,1,2,0,3,14,14,2
83,Alabama,10034,3,1,1,0,73,7,7,2
84,Alabama,10034,3,2,1,0,73,7,7,2
85,Alabama,10034,3,3,1,0,73,7,7,2
86,Alabama,10034,3,3,2,0,73,7,7,2
87,Alabama,10035,1,0,1,1,125,6,6,2
88,Alabama,10035,1,1,1,0,125,6,6,2
89,Alabama,10036,1,1,1,0,3,5,5,2
90,Alabama,10037,2,1,1,0,125,3,3,2
91,Alabama,10037,2,1,2,0,125,3,3,2
92,Alabama,10037,2,2,1,0,125,3,3,2
93,Alabama,10038,1,0,1,1,73,28,28,1
94,Alabama,10038,1,1,1,0,73,28,28,1
95,Alabama,10039,1,1,1,0,55,18,18,1
96,Alabama,10039,1,1,2,0,55,18,18,1
97,Alabama,10040,2,1,1,0,103,18,18,1
98,Alabama,10040,2,1,2,0,103,18,18,1
99,Alabama,10040,2,2,1,0,103,18,18,1
100,Alabama,10040,2,2,2,0,103,18,18,1

In [58]:

vehicle_df = pd.read_csv("FARS2020NationalCSV/vehicle.csv", encoding='latin-1')

C:\Users\Wei Kang\AppData\Local\Temp\ipykernel_13156\4028112833.py:1: DtypeWarning: Columns (14,56,58,179,181) have mixed types. Specify dtype option on import or set low_memory=False.
  vehicle_df = pd.read_csv("FARS2020NationalCSV/vehicle.csv", encoding='latin-1')

In [59]:
vehicle_df = vehicle_df.iloc[:63, [1,2,3,4,5,6,7,8,9,10]]
vehicle_df

,STATENAME,ST_CASE,VEH_NO,VE_FORMS,NUMOCCS,NUMOCCSNAME,DAY,DAYNAME,MONTH,MONTHNAME
0,Alabama,10001,1,1,4,04,1,1,1,January
1,Alabama,10002,1,4,2,02,2,2,1,January
2,Alabama,10002,2,4,1,01,2,2,1,January
3,Alabama,10002,3,4,2,02,2,2,1,January
4,Alabama,10002,4,4,1,01,2,2,1,January
5,Alabama,10003,1,2,1,01,2,2,1,January
6,Alabama,10003,2,2,1,01,2,2,1,January
7,Alabama,10004,1,1,5,05,3,3,1,January
8,Alabama,10005,1,1,1,01,4,4,1,January
9,Alabama,10006,1,2,1,01,4,4,1,January
10,Alabama,10006,2,2,2,02,4,4,1,January
11,Alabama,10007,1,1,1,01,7,7,1,January
12,Alabama,10008,1,2,1,01,8,8,1,January
13,Alabama,10008,2,2,1,01,8,8,1,January
14,Alabama,10009,1,2,1,01,9,9,1,January
15,Alabama,10009,2,2,3,03,9,9,1,January
16,Alabama,10010,1,2,2,02,10,10,1,January
17,Alabama,10010,2,2,1,01,10,10,1,January
18,Alabama,10011,1,2,1,01,10,10,1,January
19,Alabama,10011,2,2,2,02,10,10,1,January
20,Alabama,10012,1,2,1,01,11,11,1,January
21,Alabama,10012,2,2,1,01,11,11,1,January
22,Alabama,10013,1,1,1,01,13,13,1,January
23,Alabama,10014,1,1,1,01,13,13,1,January
24,Alabama,10015,1,1,1,01,13,13,1,January
25,Alabama,10016,1,2,2,02,13,13,1,January
26,Alabama,10016,2,2,1,01,13,13,1,January
27,Alabama,10017,1,2,1,01,13,13,1,January
28,Alabama,10017,2,2,1,01,13,13,1,January
29,Alabama,10018,1,2,1,01,14,14,1,January
30,Alabama,10018,2,2,3,03,14,14,1,January
31,Alabama,10019,1,1,1,01,14,14,1,January
32,Alabama,10020,1,1,1,01,15,15,1,January
33,Alabama,10021,1,2,1,01,16,16,1,January
34,Alabama,10021,2,2,1,01,16,16,1,January
35,Alabama,10022,1,1,2,02,16,16,1,January
36,Alabama,10023,1,1,1,01,17,17,1,January
37,Alabama,10024,1,2,1,01,17,17,1,January
38,Alabama,10024,2,2,1,01,17,17,1,January
39,Alabama,10025,1,1,1,01,17,17,1,January
40,Alabama,10026,1,2,1,01,17,17,1,January
41,Alabama,10026,2,2,2,02,17,17,1,January
42,Alabama,10027,1,1,2,02,18,18,1,January
43,Alabama,10028,1,1,3,03,17,17,1,January
44,Alabama,10029,1,1,1,01,12,12,1,January
45,Alabama,10030,1,2,1,01,11,11,1,January
46,Alabama,10030,2,2,2,02,11,11,1,January
47,Alabama,10031,1,3,1,01,17,17,2,February
48,Alabama,10031,2,3,2,02,17,17,2,February
49,Alabama,10031,3,3,1,01,17,17,2,February
50,Alabama,10032,1,1,1,01,17,17,2,February
51,Alabama,10033,1,1,2,02,14,14,2,February
52,Alabama,10034,1,3,1,01,7,7,2,February
53,Alabama,10034,2,3,1,01,7,7,2,February
54,Alabama,10034,3,3,2,02,7,7,2,February
55,Alabama,10035,1,1,1,01,6,6,2,February
56,Alabama,10036,1,1,1,01,5,5,2,February
57,Alabama,10037,1,2,2,02,3,3,2,February
58,Alabama,10037,2,2,1,01,3,3,2,February
59,Alabama,10038,1,1,1,01,28,28,1,January
60,Alabama,10039,1,1,2,02,18,18,1,January
61,Alabama,10040,1,2,2,02,18,18,1,January
62,Alabama,10040,2,2,2,02,18,18,1,January

In [62]:
print(vehicle_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   STATENAME    63 non-null     object
 1   ST_CASE      63 non-null     int64
 2   VEH_NO       63 non-null     int64
 3   VE_FORMS     63 non-null     int64
 4   NUMOCCS      63 non-null     int64
 5   NUMOCCSNAME  63 non-null     object
 6   DAY          63 non-null     int64
 7   DAYNAME      63 non-null     int64
 8   MONTH        63 non-null     int64
 9   MONTHNAME    63 non-null     object
dtypes: int64(7), object(3)
memory usage: 5.1+ KB
None

In [55]:
accident_df = pd.read_csv("FARS2020NationalCSV/accident.csv", encoding='latin-1')

In [56]:
accident_df = accident_df.iloc[:40, [1,2,3,4,5,6,7,8,9,10]]
accident_df

,STATENAME,ST_CASE,VE_TOTAL,VE_FORMS,PVH_INVL,PEDS,PERSONS,PERMVIT,PERNOTMVIT,COUNTY
0,Alabama,10001,1,1,0,0,4,4,0,51
1,Alabama,10002,4,4,0,0,6,6,0,73
2,Alabama,10003,2,2,0,0,2,2,0,117
3,Alabama,10004,1,1,0,0,5,5,0,15
4,Alabama,10005,1,1,0,0,1,1,0,37
5,Alabama,10006,2,2,0,0,3,3,0,103
6,Alabama,10007,1,1,0,1,1,1,1,73
7,Alabama,10008,2,2,0,0,2,2,0,25
8,Alabama,10009,2,2,0,0,4,4,0,45
9,Alabama,10010,2,2,0,0,3,3,0,95
10,Alabama,10011,2,2,0,0,3,3,0,79
11,Alabama,10012,2,2,0,0,2,2,0,73
12,Alabama,10013,1,1,0,1,1,1,1,125
13,Alabama,10014,1,1,0,0,1,1,0,53
14,Alabama,10015,1,1,0,1,1,1,1,61
15,Alabama,10016,2,2,0,0,3,3,0,43
16,Alabama,10017,2,2,0,1,2,2,1,73
17,Alabama,10018,2,2,0,0,4,4,0,43
18,Alabama,10019,1,1,0,0,1,1,0,113
19,Alabama,10020,1,1,0,0,1,1,0,73
20,Alabama,10021,2,2,0,0,2,2,0,97
21,Alabama,10022,1,1,0,0,2,2,0,9
22,Alabama,10023,1,1,0,0,1,1,0,93
23,Alabama,10024,2,2,0,0,2,2,0,81
24,Alabama,10025,1,1,0,0,1,1,0,77
25,Alabama,10026,2,2,0,0,3,3,0,115
26,Alabama,10027,1,1,0,0,2,2,0,129
27,Alabama,10028,1,1,0,0,3,3,0,73
28,Alabama,10029,1,1,0,1,1,1,1,97
29,Alabama,10030,2,2,0,0,3,3,0,87
30,Alabama,10031,3,3,0,0,4,4,0,115
31,Alabama,10032,2,1,1,0,2,1,1,73
32,Alabama,10033,1,1,0,0,2,2,0,3
33,Alabama,10034,3,3,0,0,4,4,0,73
34,Alabama,10035,1,1,0,1,1,1,1,125
35,Alabama,10036,1,1,0,0,1,1,0,3
36,Alabama,10037,2,2,0,0,3,3,0,125
37,Alabama,10038,1,1,0,1,1,1,1,73
38,Alabama,10039,1,1,0,0,2,2,0,55
39,Alabama,10040,2,2,0,0,4,4,0,103

In [49]:
print(accident_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STATENAME   40 non-null     object
 1   ST_CASE     40 non-null     int64
 2   VE_TOTAL    40 non-null     int64
 3   VE_FORMS    40 non-null     int64
 4   PVH_INVL    40 non-null     int64
 5   PEDS        40 non-null     int64
 6   PERSONS     40 non-null     int64
 7   PERMVIT     40 non-null     int64
 8   PERNOTMVIT  40 non-null     int64
 9   COUNTY      40 non-null     int64
dtypes: int64(9), object(1)
memory usage: 3.3+ KB
None

In [68]:
# Merge DataFrames by Column
personAndVehicle_df=pd.merge(person_df,vehicle_df, on=['ST_CASE', 'VEH_NO'], how='outer')
personAndVehicle_df

,STATENAME_x,ST_CASE,VE_FORMS_x,VEH_NO,PER_NO,STR_VEH,COUNTY,DAY_x,DAYNAME_x,MONTH_x,STATENAME_y,VE_FORMS_y,NUMOCCS,NUMOCCSNAME,DAY_y,DAYNAME_y,MONTH_y,MONTHNAME
0,Alabama,10001,1,1,1,0,51,1,1,1,Alabama,1.0,4.0,04,1.0,1.0,1.0,January
1,Alabama,10001,1,1,2,0,51,1,1,1,Alabama,1.0,4.0,04,1.0,1.0,1.0,January
2,Alabama,10001,1,1,3,0,51,1,1,1,Alabama,1.0,4.0,04,1.0,1.0,1.0,January
3,Alabama,10001,1,1,4,0,51,1,1,1,Alabama,1.0,4.0,04,1.0,1.0,1.0,January
4,Alabama,10002,4,1,1,0,73,2,2,1,Alabama,4.0,2.0,02,2.0,2.0,1.0,January
5,Alabama,10002,4,1,2,0,73,2,2,1,Alabama,4.0,2.0,02,2.0,2.0,1.0,January
6,Alabama,10002,4,2,1,0,73,2,2,1,Alabama,4.0,1.0,01,2.0,2.0,1.0,January
7,Alabama,10002,4,3,1,0,73,2,2,1,Alabama,4.0,2.0,02,2.0,2.0,1.0,January
8,Alabama,10002,4,3,2,0,73,2,2,1,Alabama,4.0,2.0,02,2.0,2.0,1.0,January
9,Alabama,10002,4,4,1,0,73,2,2,1,Alabama,4.0,1.0,01,2.0,2.0,1.0,January
10,Alabama,10003,2,1,1,0,117,2,2,1,Alabama,2.0,1.0,01,2.0,2.0,1.0,January
11,Alabama,10003,2,2,1,0,117,2,2,1,Alabama,2.0,1.0,01,2.0,2.0,1.0,January
12,Alabama,10004,1,1,1,0,15,3,3,1,Alabama,1.0,5.0,05,3.0,3.0,1.0,January
13,Alabama,10004,1,1,2,0,15,3,3,1,Alabama,1.0,5.0,05,3.0,3.0,1.0,January
14,Alabama,10004,1,1,3,0,15,3,3,1,Alabama,1.0,5.0,05,3.0,3.0,1.0,January
15,Alabama,10004,1,1,4,0,15,3,3,1,Alabama,1.0,5.0,05,3.0,3.0,1.0,January
16,Alabama,10004,1,1,5,0,15,3,3,1,Alabama,1.0,5.0,05,3.0,3.0,1.0,January
17,Alabama,10005,1,1,1,0,37,4,4,1,Alabama,1.0,1.0,01,4.0,4.0,1.0,January
18,Alabama,10006,2,1,1,0,103,4,4,1,Alabama,2.0,1.0,01,4.0,4.0,1.0,January
19,Alabama,10006,2,2,1,0,103,4,4,1,Alabama,2.0,2.0,02,4.0,4.0,1.0,January
20,Alabama,10006,2,2,2,0,103,4,4,1,Alabama,2.0,2.0,02,4.0,4.0,1.0,January
21,Alabama,10007,1,0,1,1,73,7,7,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Alabama,10007,1,1,1,0,73,7,7,1,Alabama,1.0,1.0,01,7.0,7.0,1.0,January
23,Alabama,10008,2,1,1,0,25,8,8,1,Alabama,2.0,1.0,01,8.0,8.0,1.0,January
24,Alabama,10008,2,2,1,0,25,8,8,1,Alabama,2.0,1.0,01,8.0,8.0,1.0,January
25,Alabama,10009,2,1,1,0,45,9,9,1,Alabama,2.0,1.0,01,9.0,9.0,1.0,January
26,Alabama,10009,2,2,1,0,45,9,9,1,Alabama,2.0,3.0,03,9.0,9.0,1.0,January
27,Alabama,10009,2,2,2,0,45,9,9,1,Alabama,2.0,3.0,03,9.0,9.0,1.0,January
28,Alabama,10009,2,2,3,0,45,9,9,1,Alabama,2.0,3.0,03,9.0,9.0,1.0,January
29,Alabama,10010,2,1,1,0,95,10,10,1,Alabama,2.0,2.0,02,10.0,10.0,1.0,January
30,Alabama,10010,2,1,2,0,95,10,10,1,Alabama,2.0,2.0,02,10.0,10.0,1.0,January
31,Alabama,10010,2,2,1,0,95,10,10,1,Alabama,2.0,1.0,01,10.0,10.0,1.0,January
32,Alabama,10011,2,1,1,0,79,10,10,1,Alabama,2.0,1.0,01,10.0,10.0,1.0,January
33,Alabama,10011,2,2,1,0,79,10,10,1,Alabama,2.0,2.0,02,10.0,10.0,1.0,January
34,Alabama,10011,2,2,2,0,79,10,10,1,Alabama,2.0,2.0,02,10.0,10.0,1.0,January
35,Alabama,10012,2,1,1,0,73,11,11,1,Alabama,2.0,1.0,01,11.0,11.0,1.0,January
36,Alabama,10012,2,2,1,0,73,11,11,1,Alabama,2.0,1.0,01,11.0,11.0,1.0,January
37,Alabama,10013,1,0,1,1,125,13,13,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Alabama,10013,1,1,1,0,125,13,13,1,Alabama,1.0,1.0,01,13.0,13.0,1.0,January
39,Alabama,10014,1,1,1,0,53,13,13,1,Alabama,1.0,1.0,01,13.0,13.0,1.0,January
40,Alabama,10015,1,0,1,1,61,13,13,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Alabama,10015,1,1,1,0,61,13,13,1,Alabama,1.0,1.0,01,13.0,13.0,1.0,January
42,Alabama,10016,2,1,1,0,43,13,13,1,Alabama,2.0,2.0,02,13.0,13.0,1.0,January
43,Alabama,10016,2,1,2,0,43,13,13,1,Alabama,2.0,2.0,02,13.0,13.0,1.0,January
44,Alabama,10016,2,2,1,0,43,13,13,1,Alabama,2.0,1.0,01,13.0,13.0,1.0,January
45,Alabama,10017,2,0,1,1,73,13,13,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Alabama,10017,2,1,1,0,73,13,13,1,Alabama,2.0,1.0,01,13.0,13.0,1.0,January
47,Alabama,10017,2,2,1,0,73,13,13,1,Alabama,2.0,1.0,01,13.0,13.0,1.0,January
48,Alabama,10018,2,1,1,0,43,14,14,1,Alabama,2.0,1.0,01,14.0,14.0,1.0,January
49,Alabama,10018,2,2,1,0,43,14,14,1,Alabama,2.0,3.0,03,14.0,14.0,1.0,January
50,Alabama,10018,2,2,2,0,43,14,14,1,Alabama,2.0,3.0,03,14.0,14.0,1.0,January
51,Alabama,10018,2,2,3,0,43,14,14,1,Alabama,2.0,3.0,03,14.0,14.0,1.0,January
52,Alabama,10019,1,1,1,0,113,14,14,1,Alabama,1.0,1.0,01,14.0,14.0,1.0,January
53,Alabama,10020,1,1,1,0,73,15,15,1,Alabama,1.0,1.0,01,15.0,15.0,1.0,January
54,Alabama,10021,2,1,1,0,97,16,16,1,Alabama,2.0,1.0,01,16.0,16.0,1.0,January
55,Alabama,10021,2,2,1,0,97,16,16,1,Alabama,2.0,1.0,01,16.0,16.0,1.0,January
56,Alabama,10022,1,1,1,0,9,16,16,1,Alabama,1.0,2.0,02,16.0,16.0,1.0,January
57,Alabama,10022,1,1,2,0,9,16,16,1,Alabama,1.0,2.0,02,16.0,16.0,1.0,January
58,Alabama,10023,1,1,1,0,93,17,17,1,Alabama,1.0,1.0,01,17.0,17.0,1.0,January
59,Alabama,10024,2,1,1,0,81,17,17,1,Alabama,2.0,1.0,01,17.0,17.0,1.0,January
60,Alabama,10024,2,2,1,0,81,17,17,1,Alabama,2.0,1.0,01,17.0,17.0,1.0,January
61,Alabama,10025,1,1,1,0,77,17,17,1,Alabama,1.0,1.0,01,17.0,17.0,1.0,January
62,Alabama,10026,2,1,1,0,115,17,17,1,Alabama,2.0,1.0,01,17.0,17.0,1.0,January
63,Alabama,10026,2,2,1,0,115,17,17,1,Alabama,2.0,2.0,02,17.0,17.0,1.0,January
64,Alabama,10026,2,2,2,0,115,17,17,1,Alabama,2.0,2.0,02,17.0,17.0,1.0,January
65,Alabama,10027,1,1,1,0,129,18,18,1,Alabama,1.0,2.0,02,18.0,18.0,1.0,January
66,Alabama,10027,1,1,2,0,129,18,18,1,Alabama,1.0,2.0,02,18.0,18.0,1.0,January
67,Alabama,10028,1,1,1,0,73,17,17,1,Alabama,1.0,3.0,03,17.0,17.0,1.0,January
68,Alabama,10028,1,1,2,0,73,17,17,1,Alabama,1.0,3.0,03,17.0,17.0,1.0,January
69,Alabama,10028,1,1,3,0,73,17,17,1,Alabama,1.0,3.0,03,17.0,17.0,1.0,January
70,Alabama,10029,1,0,1,1,97,12,12,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Alabama,10029,1,1,1,0,97,12,12,1,Alabama,1.0,1.0,01,12.0,12.0,1.0,January
72,Alabama,10030,2,1,1,0,87,11,11,1,Alabama,2.0,1.0,01,11.0,11.0,1.0,January
73,Alabama,10030,2,2,1,0,87,11,11,1,Alabama,2.0,2.0,02,11.0,11.0,1.0,January
74,Alabama,10030,2,2,2,0,87,11,11,1,Alabama,2.0,2.0,02,11.0,11.0,1.0,January
75,Alabama,10031,3,1,1,0,115,17,17,2,Alabama,3.0,1.0,01,17.0,17.0,2.0,February
76,Alabama,10031,3,2,1,0,115,17,17,2,Alabama,3.0,2.0,02,17.0,17.0,2.0,February
77,Alabama,10031,3,2,2,0,115,17,17,2,Alabama,3.0,2.0,02,17.0,17.0,2.0,February
78,Alabama,10031,3,3,1,0,115,17,17,2,Alabama,3.0,1.0,01,17.0,17.0,2.0,February
79,Alabama,10032,1,1,1,0,73,17,17,2,Alabama,1.0,1.0,01,17.0,17.0,2.0,February
80,Alabama,10032,1,2,1,0,73,17,17,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,Alabama,10033,1,1,1,0,3,14,14,2,Alabama,1.0,2.0,02,14.0,14.0,2.0,February
82,Alabama,10033,1,1,2,0,3,14,14,2,Alabama,1.0,2.0,02,14.0,14.0,2.0,February
83,Alabama,10034,3,1,1,0,73,7,7,2,Alabama,3.0,1.0,01,7.0,7.0,2.0,February
84,Alabama,10034,3,2,1,0,73,7,7,2,Alabama,3.0,1.0,01,7.0,7.0,2.0,February
85,Alabama,10034,3,3,1,0,73,7,7,2,Alabama,3.0,2.0,02,7.0,7.0,2.0,February
86,Alabama,10034,3,3,2,0,73,7,7,2,Alabama,3.0,2.0,02,7.0,7.0,2.0,February
87,Alabama,10035,1,0,1,1,125,6,6,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,Alabama,10035,1,1,1,0,125,6,6,2,Alabama,1.0,1.0,01,6.0,6.0,2.0,February
89,Alabama,10036,1,1,1,0,3,5,5,2,Alabama,1.0,1.0,01,5.0,5.0,2.0,February
90,Alabama,10037,2,1,1,0,125,3,3,2,Alabama,2.0,2.0,02,3.0,3.0,2.0,February
91,Alabama,10037,2,1,2,0,125,3,3,2,Alabama,2.0,2.0,02,3.0,3.0,2.0,February
92,Alabama,10037,2,2,1,0,125,3,3,2,Alabama,2.0,1.0,01,3.0,3.0,2.0,February
93,Alabama,10038,1,0,1,1,73,28,28,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,Alabama,10038,1,1,1,0,73,28,28,1,Alabama,1.0,1.0,01,28.0,28.0,1.0,January
95,Alabama,10039,1,1,1,0,55,18,18,1,Alabama,1.0,2.0,02,18.0,18.0,1.0,January
96,Alabama,10039,1,1,2,0,55,18,18,1,Alabama,1.0,2.0,02,18.0,18.0,1.0,January
97,Alabama,10040,2,1,1,0,103,18,18,1,Alabama,2.0,2.0,02,18.0,18.0,1.0,January
98,Alabama,10040,2,1,2,0,103,18,18,1,Alabama,2.0,2.0,02,18.0,18.0,1.0,January
99,Alabama,10040,2,2,1,0,103,18,18,1,Alabama,2.0,2.0,02,18.0,18.0,1.0,January
100,Alabama,10040,2,2,2,0,103,18,18,1,Alabama,2.0,2.0,02,18.0,18.0,1.0,January

After joining, there will be some rows with NAN on the right side (from vehicles.df). This is because these rows don't exist in the original vehicles.csv. So when i join them, its nan. I will try to drop them later.

In [64]:
# Merge DataFrames by Column
three_df=pd.merge(personAndVehicle_df,accident_df, on=['ST_CASE'], how='outer')
three_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   STATENAME  101 non-null    object
 1   ST_CASE    101 non-null    int64
 2   VE_FORMS   101 non-null    int64
 3   VEH_NO     101 non-null    int64
 4   PER_NO     101 non-null    int64
 5   STR_VEH    101 non-null    int64
 6   COUNTY     101 non-null    int64
 7   DAY        101 non-null    int64
 8   DAYNAME    101 non-null    int64
 9   MONTH      101 non-null    int64
dtypes: int64(9), object(1)
memory usage: 8.0+ KB
None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   STATENAME    63 non-null     object
 1   ST_CASE      63 non-null     int64
 2   VEH_NO       63 non-null     int64
 3   VE_FORMS     63 non-null     int64
 4   NUMOCCS      63 non-null     int64
 5   NUMOCCSNAME  63 non-null     object
 6   DAY          63 non-null     int64
 7   DAYNAME      63 non-null     int64
 8   MONTH        63 non-null     int64
 9   MONTHNAME    63 non-null     object
dtypes: int64(7), object(3)
memory usage: 5.1+ KB
None